hmrc/birth-registration-matching-proxy

app/uk/gov/hmrc/brm/connectors/BirthConnector.scala
app/uk/gov/hmrc/brm/controllers/MatchingController.scala
test/uk/gov/hmrc/brm/controllers/MatchingControllerSpec.scala

- handling additional http responses from GRO

Exceptions

---

app/uk/gov/hmrc/brm/connectors/BirthConnector.scala
app/uk/gov/hmrc/brm/controllers/MatchingController.scala
app/uk/gov/hmrc/brm/tls/TLSFactory.scala
app/uk/gov/hmrc/brm/utils/BrmLogger.scala
app/uk/gov/hmrc/brm/utils/KeyHolder.scala
test/utils/BrmLoggerSpec.scala

created BRM logger to log more information about request, to track it back to matching.

Brms 76 better logs

---

conf/application.conf

BRMS-45-sensu-alert: updated date for sensu alert.

---

conf/application.conf

BRMS-45-revert: revert date change.

---

project/MicroServiceBuild.scala

@adamconder @chris-ianson @manishsw 
Updated proxy service dependency.

dependency :Updated dependencies

---

app/uk/gov/hmrc/brm/config/microserviceGlobal.scala
app/uk/gov/hmrc/brm/connectors/BirthConnector.scala
conf/application.conf
test/uk/gov/hmrc/brm/BRMFakeApplication.scala
test/uk/gov/hmrc/brm/connectors/BirthConnectorSpec.scala

Attempting to make multiple requests if we receive a timeout exception in proxy to GRO.

Multiple attempts

---

app/uk/gov/hmrc/brm/config/microserviceGlobal.scala
app/uk/gov/hmrc/brm/config/microserviceWiring.scala
conf/application.conf
project/MicroServiceBuild.scala

- removing authentication filter from proxy
- removing baseUrl override method

remove auth filter

---

app/uk/gov/hmrc/brm/controllers/MatchingController.scala
app/uk/gov/hmrc/brm/utils/AccessTokenRepository.scala
test/uk/gov/hmrc/brm/connectors/AuthenticatorSpec.scala
test/utils/AccessTokenRepositorySpec.scala

- updated to expire token before 60 seconds.

token_expired: updated to fix token expiry.

---

app/uk/gov/hmrc/brm/connectors/ResponseHandler.scala

Changing to handle additional client side errors and log appropriately.

BRMS-121: fix ResponseHandler logging

---

app/uk/gov/hmrc/brm/config/microserviceGlobal.scala
app/uk/gov/hmrc/brm/config/microserviceWiring.scala
conf/application-logger.xml
conf/application.conf
test/uk/gov/hmrc/brm/config/BRMResultHandlerSpec.scala

updated to audit body when datastream is down.

Brms 151 datastream

---

app/uk/gov/hmrc/brm/config/microserviceGlobal.scala
app/uk/gov/hmrc/brm/config/microserviceWiring.scala
conf/application.conf
test/uk/gov/hmrc/brm/config/BRMResultHandlerSpec.scala

added switch to on/off audit logging.

BRMS-151-switch: added switch of audit logging.

---

conf/application-json-logger.xml
conf/logback.xml

Set logger to ERROR level for beeconsultants and sun.net

---

app/uk/gov/hmrc/brm/connectors/ResponseHandler.scala

@manishsw I've picked out the refactor and placed this onto a new branch. This should be OK to merge

Change WARN to INFO level for client errors

---

test/uk/gov/hmrc/brm/controllers/MatchingControllerSpec.scala

@adamconder @anujakhare @manishsw 
Invalid dob test updated to return BadGateway. Tested through postman against fix in stub (see other pull request)

Update invalid dob to return BadGateway

---

project/MicroServiceBuild.scala
project/plugins.sbt

Updated library for Play-2.5.12

BRMS-273:Updated library for Play-2.5.12

---

app/uk/gov/hmrc/brm/config/microserviceGlobal.scala
app/uk/gov/hmrc/brm/connectors/Authenticator.scala
app/uk/gov/hmrc/brm/connectors/BirthConnector.scala
app/uk/gov/hmrc/brm/tls/TLSFactory.scala
app/uk/gov/hmrc/brm/utils/CertificateStatus.scala
conf/application.conf
test/uk/gov/hmrc/brm/connectors/AuthenticatorSpec.scala
test/uk/gov/hmrc/brm/connectors/BirthConnectorSpec.scala
test/uk/gov/hmrc/brm/utils/CertificateStatusSpec.scala

BRMS-425: authentication changes

---

app/uk/gov/hmrc/brm/config/microserviceGlobal.scala
app/uk/gov/hmrc/brm/connectors/Authenticator.scala
app/uk/gov/hmrc/brm/connectors/BirthConnector.scala
app/uk/gov/hmrc/brm/connectors/ProxyAuthenticator.scala
app/uk/gov/hmrc/brm/tls/TLSFactory.scala
conf/application.conf
test/uk/gov/hmrc/brm/connectors/ProxyAuthenticatorSpec.scala

Removed proxy call through additional headers and added proxy details to bigbee request

Add Proxy config to bigbee request

---

app/uk/gov/hmrc/brm/connectors/ProxyAuthenticator.scala

@adamconder Merge, merge, merge!!!

Base64c decode password

---

app/uk/gov/hmrc/brm/connectors/ProxyAuthenticator.scala

@adamconder Removing logs and merging

Remove logs

---

conf/application.conf

Fix year to be able to run it local and in jenkins ( for tests )

DDCNOS-6018: Try to fix certificate expiry date

---

app/uk/gov/hmrc/brm/connectors/Authenticator.scala

Implement this feature to be used in local and dev boxes, please review

DDCNOS-6018: check if tls is enabled for (local and dev box) to be used

---

conf/application.conf

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

[RS][DDCE-1288] Updated password pulling from.

---

.gitignore
app/uk/gov/hmrc/brm/config/ModuleBindings.scala
app/uk/gov/hmrc/brm/connectors/Authenticator.scala
app/uk/gov/hmrc/brm/connectors/GROEnglandAndWalesConnector.scala
app/uk/gov/hmrc/brm/controllers/MatchingController.scala
app/uk/gov/hmrc/brm/http/ProxyEnabledHttpClient.scala
build.sbt
conf/application.conf
project/build.properties
project/plugins.sbt
test/uk/gov/hmrc/brm/TestFixture.scala
test/uk/gov/hmrc/brm/connectors/GROEnglandAndWalesConnectorSpec.scala
test/uk/gov/hmrc/brm/controllers/MatchingControllerSpec.scala
test/uk/gov/hmrc/brm/http/ProxyEnabledHttpClientSpec.scala
test/uk/gov/hmrc/brm/utils/EncoderSpec.scala

- Bootstrap 2.3.0 -> 5.3.0
- Play 2.6.25 -> 2.7.9
- Sbt 1.3.13 -> 1.4.9
- General depedency bumps

[EH][DDCE-1907] Play 2.7.9 & Bootstrap 5.3.0 Upgrade

---

app/uk/gov/hmrc/brm/connectors/GROEnglandAndWalesConnector.scala
app/uk/gov/hmrc/brm/connectors/ResponseHandler.scala
app/uk/gov/hmrc/brm/utils/BrmLogger.scala
build.sbt
project/plugins.sbt
test/uk/gov/hmrc/brm/TestFixture.scala
test/uk/gov/hmrc/brm/http/ProxyEnabledHttpClientSpec.scala
test/uk/gov/hmrc/brm/utils/EncoderSpec.scala

- Service and dependencies updated to Play 2.8 versioning

[DDCE-2034][EH] Play 2.8 upgrade

---

app/uk/gov/hmrc/brm/connectors/Authenticator.scala
app/uk/gov/hmrc/brm/connectors/GROEnglandAndWalesConnector.scala
app/uk/gov/hmrc/brm/http/CustomAhcWSModule.scala
app/uk/gov/hmrc/brm/http/ProxyEnabledHttpClient.scala
app/uk/gov/hmrc/brm/utils/AccessTokenRepository.scala
app/uk/gov/hmrc/brm/utils/CertificateStatus.scala
app/uk/gov/hmrc/brm/utils/DateOutput.scala
app/uk/gov/hmrc/brm/utils/TimeProvider.scala
build.sbt
conf/application.conf
conf/logback.xml
conf/prod.routes
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/uk/gov/hmrc/brm/connectors/AuthenticatorSpec.scala
test/uk/gov/hmrc/brm/connectors/GROEnglandAndWalesConnectorSpec.scala
test/uk/gov/hmrc/brm/controllers/MatchingControllerSpec.scala
test/uk/gov/hmrc/brm/http/ProxyEnabledHttpClientSpec.scala
test/uk/gov/hmrc/brm/utils/AccessTokenRepositorySpec.scala
test/uk/gov/hmrc/brm/utils/CertificateStatusSpec.scala
test/uk/gov/hmrc/brm/utils/DateOutputSpec.scala

DDCE 5137 - Play 3.0 Migration & Joda Time removal

DDCE 5137 - Play 3.0 Migration & Joda Time removal
